name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [16.x]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build
        run: nr build

      - name: Build Unpacked Plugin
        run: |
          mkdir logseq-dictionary
          cp package.json README.md logseq-dictionary
          mv dist logseq-dictionary

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open

      - uses: actions/upload-artifact@v3
        with:
          name: logseq-dictionary-${{ steps.findPr.outputs.pr }}
          path: logseq-dictionary
